=== amsa-code/sgb-decoder/src/main/resources/detection-schema.json
{
  "$id" : "https://amsa.gov.au/sgb",
  "$schema" : "http://json-schema.org/draft/2019-09/schema",
  "definitions" : {
    "AircraftOperatorAndSerialNumber" : {
      "type" : "object",
      "properties" : {
        "vesselIdType" : {
          "$ref" : "#/definitions/VesselIdType"
        },
        "aircraftOperatorDesignator" : {
          "type" : "string"
        },
        "serialNumber" : {
          "type" : "integer"
        }
      },
      "required" : [ "vesselIdType", "aircraftOperatorDesignator", "serialNumber" ]
    },
    "Mmsi" : {
      "type" : "object",
      "properties" : {
        "vesselIdType" : {
          "$ref" : "#/definitions/VesselIdType"
        },
        "mmsi" : {
          "type" : "integer"
        },
        "epirbMmsi" : {
          "type" : "integer"
        }
      },
      "required" : [ "vesselIdType" ]
    },
    "ObjectiveRequirements" : {
      "type" : "object",
      "properties" : {
        "rotatingFieldType" : {
          "$ref" : "#/definitions/RotatingFieldType"
        },
        "elapsedTimeSinceActivationHours" : {
          "type" : "integer"
        },
        "timeSinceLastEncodedLocationMinutes" : {
          "type" : "integer"
        },
        "altitudeEncodedLocationMetres" : {
          "type" : "integer"
        },
        "dilutionPrecisionHdop" : {
          "$ref" : "#/definitions/Range"
        },
        "dilutionPrecisionVdop" : {
          "$ref" : "#/definitions/Range"
        },
        "activationMethod" : {
          "$ref" : "#/definitions/ActivationMethod"
        },
        "remainingBatteryCapacityPercent" : {
          "$ref" : "#/definitions/Range"
        },
        "gnssStatus" : {
          "$ref" : "#/definitions/GnssStatus"
        }
      },
      "required" : [ "rotatingFieldType", "elapsedTimeSinceActivationHours", "timeSinceLastEncodedLocationMinutes", "altitudeEncodedLocationMetres", "activationMethod", "gnssStatus" ]
    },
    "RlsType" : {
      "type" : "string",
      "enum" : [ "ACKNOWLEDGEMENT_SERVICE", "TEST_SERVICE", "OTHER" ]
    },
    "DeactivationMethod" : {
      "type" : "string",
      "enum" : [ "MANUAL_DEACTIVATION_BY_USER", "AUTOMATIC_DEACTIVATION_BY_EXTERNAL_MEANS", "OTHER" ]
    },
    "ActivationMethod" : {
      "type" : "string",
      "enum" : [ "MANUAL_ACTIVATION_BY_USER", "AUTOMATIC_ACTIVATION_BY_BEACON", "AUTOMATIC_ACTIVATION_BY_EXTERNAL_MEANS", "OTHER" ]
    },
    "BeaconFeedback" : {
      "type" : "object",
      "properties" : {
        "rlmType1FeedbackReceived" : {
          "type" : "boolean"
        },
        "rlmType2FeedbackReceived" : {
          "type" : "boolean"
        },
        "rlsType" : {
          "$ref" : "#/definitions/RlsType"
        },
        "shortRlmParametersBitString" : {
          "type" : "string"
        }
      },
      "required" : [ "rlmType1FeedbackReceived", "rlmType2FeedbackReceived", "rlsType" ]
    },
    "UnknownRotatingField" : {
      "type" : "object",
      "properties" : {
        "rotatingFieldType" : {
          "$ref" : "#/definitions/RotatingFieldType"
        },
        "bitString" : {
          "type" : "string"
        }
      },
      "required" : [ "rotatingFieldType", "bitString" ]
    },
    "Range" : {
      "type" : "object",
      "properties" : {
        "min" : {
          "$ref" : "#/definitions/RangeEnd"
        },
        "max" : {
          "$ref" : "#/definitions/RangeEnd"
        }
      }
    },
    "TriggeringEvent" : {
      "type" : "string",
      "enum" : [ "MANUAL_ACTIVATION_BY_CREW", "G_SWITCH_OR_DEFORMATION_ACTIVATION", "AUTOMATIC_ACTIVATION_FROM_AVIONICS_OR_TRIGGERING_SYSTEM", "OTHER" ]
    },
    "RadioCallSign" : {
      "type" : "object",
      "properties" : {
        "vesselIdType" : {
          "$ref" : "#/definitions/VesselIdType"
        },
        "value" : {
          "type" : "string"
        }
      },
      "required" : [ "vesselIdType" ]
    },
    "RangeEnd" : {
      "type" : "object",
      "properties" : {
        "value" : {
          "type" : "integer"
        },
        "exclusive" : {
          "type" : "boolean"
        }
      },
      "required" : [ "value", "exclusive" ]
    },
    "Aviation24BitAddress" : {
      "type" : "object",
      "properties" : {
        "vesselIdType" : {
          "$ref" : "#/definitions/VesselIdType"
        },
        "addressHex" : {
          "type" : "string"
        },
        "aircraftOperatorDesignator" : {
          "type" : "string"
        }
      },
      "required" : [ "vesselIdType", "addressHex" ]
    },
    "RotatingFieldType" : {
      "type" : "string",
      "enum" : [ "CANCELLATION", "ELT_DT_IN_FLIGHT_EMERGENCY", "NATIONAL_USE", "OBJECTIVE_REQUIREMENTS", "RLS", "UNKNOWN" ]
    },
    "VesselId" : {
      "oneOf" : [ {
        "$ref" : "#/definitions/AircraftOperatorAndSerialNumber"
      }, {
        "$ref" : "#/definitions/AircraftRegistrationMarking"
      }, {
        "$ref" : "#/definitions/Aviation24BitAddress"
      }, {
        "$ref" : "#/definitions/Mmsi"
      }, {
        "$ref" : "#/definitions/RadioCallSign"
      } ]
    },
    "RlsProvider" : {
      "type" : "string",
      "enum" : [ "GALILEO", "GLONASS", "OTHER" ]
    },
    "EncodedGnssPosition" : {
      "type" : "object",
      "properties" : {
        "lat" : {
          "type" : "number"
        },
        "lon" : {
          "type" : "number"
        }
      },
      "required" : [ "lat", "lon" ]
    },
    "Cancellation" : {
      "type" : "object",
      "properties" : {
        "rotatingFieldType" : {
          "$ref" : "#/definitions/RotatingFieldType"
        },
        "deactivationMethod" : {
          "$ref" : "#/definitions/DeactivationMethod"
        }
      },
      "required" : [ "rotatingFieldType", "deactivationMethod" ]
    },
    "Detection" : {
      "type" : "object",
      "properties" : {
        "tac" : {
          "type" : "integer"
        },
        "serialNo" : {
          "type" : "integer"
        },
        "countryCode" : {
          "type" : "integer"
        },
        "hasAtLeastOneEnabledHomingSignal" : {
          "type" : "boolean"
        },
        "hasEnabledRls" : {
          "type" : "boolean"
        },
        "testProtocolMessage" : {
          "type" : "boolean"
        },
        "encodedGnssPosition" : {
          "$ref" : "#/definitions/EncodedGnssPosition"
        },
        "vesselId" : {
          "$ref" : "#/definitions/VesselId"
        },
        "beaconType" : {
          "$ref" : "#/definitions/BeaconType"
        },
        "rotatingField" : {
          "$ref" : "#/definitions/RotatingField"
        },
        "beacon23HexId" : {
          "type" : "string"
        },
        "beacon15HexId" : {
          "type" : "string"
        }
      },
      "required" : [ "tac", "serialNo", "countryCode", "hasAtLeastOneEnabledHomingSignal", "hasEnabledRls", "testProtocolMessage", "beaconType", "rotatingField", "beacon23HexId", "beacon15HexId" ]
    },
    "VesselIdType" : {
      "type" : "string",
      "enum" : [ "AIRCRAFT_OPERATOR_AND_SERIAL_NUMBER", "AIRCRAFT_REGISTRATION_MARKING", "AVIATION_24_BIT_ADDRESS", "MMSI", "RADIO_CALL_SIGN" ]
    },
    "EltDtInFlightEmergency" : {
      "type" : "object",
      "properties" : {
        "rotatingFieldType" : {
          "$ref" : "#/definitions/RotatingFieldType"
        },
        "timeOfLastEncodedLocation" : {
          "type" : "string",
          "format" : "time"
        },
        "altitudeEncodedLocationMetres" : {
          "type" : "integer"
        },
        "triggeringEvent" : {
          "$ref" : "#/definitions/TriggeringEvent"
        },
        "gnssStatus" : {
          "$ref" : "#/definitions/GnssStatus"
        },
        "remainingBatteryCapacityPercent" : {
          "$ref" : "#/definitions/Range"
        }
      },
      "required" : [ "rotatingFieldType", "timeOfLastEncodedLocation", "altitudeEncodedLocationMetres", "triggeringEvent", "gnssStatus" ]
    },
    "NationalUse" : {
      "type" : "object",
      "properties" : {
        "rotatingFieldType" : {
          "$ref" : "#/definitions/RotatingFieldType"
        },
        "bitString" : {
          "type" : "string"
        }
      },
      "required" : [ "rotatingFieldType", "bitString" ]
    },
    "GnssStatus" : {
      "type" : "string",
      "enum" : [ "NO_FIX", "LOCATION_2D", "LOCATION_3D", "OTHER" ]
    },
    "AircraftRegistrationMarking" : {
      "type" : "object",
      "properties" : {
        "vesselIdType" : {
          "$ref" : "#/definitions/VesselIdType"
        },
        "value" : {
          "type" : "string"
        }
      },
      "required" : [ "vesselIdType" ]
    },
    "BeaconType" : {
      "type" : "string",
      "enum" : [ "ELT_NOT_DT", "EPIRB", "PLB", "ELT_DT", "SYSTEM", "OTHER" ]
    },
    "RotatingField" : {
      "oneOf" : [ {
        "$ref" : "#/definitions/Cancellation"
      }, {
        "$ref" : "#/definitions/EltDtInFlightEmergency"
      }, {
        "$ref" : "#/definitions/NationalUse"
      }, {
        "$ref" : "#/definitions/ObjectiveRequirements"
      }, {
        "$ref" : "#/definitions/Rls"
      }, {
        "$ref" : "#/definitions/UnknownRotatingField"
      } ]
    },
    "Rls" : {
      "type" : "object",
      "properties" : {
        "rotatingFieldType" : {
          "$ref" : "#/definitions/RotatingFieldType"
        },
        "canProcessAutomaticallyGeneratedAckRlmType1" : {
          "type" : "boolean"
        },
        "canProcessManuallyGeneratedRlm" : {
          "type" : "boolean"
        },
        "rlsProvider" : {
          "$ref" : "#/definitions/RlsProvider"
        },
        "beaconFeedback" : {
          "$ref" : "#/definitions/BeaconFeedback"
        }
      },
      "required" : [ "rotatingFieldType", "canProcessAutomaticallyGeneratedAckRlmType1", "canProcessManuallyGeneratedRlm", "rlsProvider" ]
    }
  },
  "$ref" : "#/definitions/Detection"
}

=== amsa-code/sgb-decoder/src/test/resources/compliance-kit/detection-with-aircraft-operator-and-serial-number.json
{
  "tac" : 230,
  "serialNo" : 573,
  "countryCode" : 201,
  "hasAtLeastOneEnabledHomingSignal" : true,
  "hasEnabledRls" : false,
  "testProtocolMessage" : false,
  "encodedGnssPosition" : {
    "lat" : 48.79315185546875,
    "lon" : 69.00875854492188
  },
  "vesselId" : {
    "vesselIdType" : "AIRCRAFT_OPERATOR_AND_SERIAL_NUMBER",
    "aircraftOperatorDesignator" : "XYZ",
    "serialNumber" : 15
  },
  "beaconType" : "ELT_NOT_DT",
  "rotatingField" : {
    "rotatingFieldType" : "OBJECTIVE_REQUIREMENTS",
    "elapsedTimeSinceActivationHours" : 1,
    "timeSinceLastEncodedLocationMinutes" : 6,
    "altitudeEncodedLocationMetres" : 432,
    "dilutionPrecisionHdop" : {
      "min" : {
        "value" : 0,
        "exclusive" : false
      },
      "max" : {
        "value" : 1,
        "exclusive" : false
      }
    },
    "dilutionPrecisionVdop" : {
      "min" : {
        "value" : 1,
        "exclusive" : true
      },
      "max" : {
        "value" : 2,
        "exclusive" : false
      }
    },
    "activationMethod" : "MANUAL_ACTIVATION_BY_USER",
    "remainingBatteryCapacityPercent" : {
      "min" : {
        "value" : 75,
        "exclusive" : true
      },
      "max" : {
        "value" : 100,
        "exclusive" : false
      }
    },
    "gnssStatus" : "LOCATION_3D"
  },
  "beacon23HexId" : "9934039823D5BD6201E0000",
  "beacon15HexId" : "9934039823D5BD6"
}
